const glassDetails = {
  'Flute Glass': 'The world of champagne lends elegance to certain types of beer. Long and narrow bodies ensure that carbonation doesn\'t dissipate too quickly and showcase a lively carbonation or sparkling color. Stems will often be a bit shorter than the traditional champagne glass, but not necessarily. Benefits: Enhances and showcases carbonation. Releases volatiles quickly for a more intense upfront aroma.',
  'Goblet (or Chalice)': 'Majestic pieces of work, ranging from delicate and long stemmed (Goblet) to heavy and thick walled (Chalice). The more delicate ones may also have their rims laced with silver or gold, while the heavy boast sculpture-like stems. Some are designed to maintain a 2-centimeter head. This is achieved by scoring the inside bottom of the glass, which creates a CO2 nucleation point, and a stream of eternal bubbles and perfect head retention as a result. Benefits: Eye candy. Designed to maintain head. Wide-mouthed for deep sips.',
  'Mug (or Seidel, Stein)': 'Heavy, sturdy, large and with handle, the mug is a fun and serious piece of glassware that comes in many sizes and shapes. The best part of using a mug is that you can clink them together with more confidence than other types of glassware, and they hold loads of beer. Seidel is a German mug, while a Stein is the stone equivalent that traditionally features a lid, the use of which dates back to the Black Plague to prevent flies from dropping in. Benefits: Easy to drink out of. Holds plenty of volume.',
  'Pilsner Glass (or Pokal)': 'Typically a tall, slender and tapered 12-ounce glass, shaped like a trumpet at times, that captures the sparkling effervesces and colors of a Pils while maintaining its head. A Pokal is a European Pilsner glass with a stem. Benefits: Showcases color, clarity and carbonation. Promotes head retention. Enhances volatiles.',
  'Pint Glass (or Becker, Nonic, Tumbler)': 'Near cylindrical, with a slight taper and wide-mouth. There are two standard sizes, the 16-ounce (US Tumbler - the pour man\'s pint glass and most common) or the 20-ounce Imperial (Nonic), which has a slight ridge towards the top, a grip of sorts and helps in stacking them. The 20-ounce version is preferred to accommodate more beer or beers with large crowning heads. A Becker is the German equivalent, tapering at the top. Benefits: Cheap to make. Easy to store. Easy to drink out of.',
  'Snifter': 'Used for brandy and cognac, these wide-bowled and stemmed glasses with their tapered mouths are perfect for capturing the aromas of strong ales. Volumes range, but they all provide room to swirl and agitate volatiles. Benefits: Captures and enhances volatiles.',
  'Stange (Slender Cylinder)': 'A traditional German glass, stange means "stick" and these tall, slender cylinders are used to serve more delicate beers, amplifying malt and hop nuances. Substitute with a Tom Collins glass. Benefits: Tighter concentration of volatiles.',
  'Tulip': 'A stemmed glass, obviously tulip-shaped, wherein the top of the glass pushes out a bit to form a lip in order to capture the head and the body is bulbous. Scotch Ales are often served in a "thistle glass," which is a modified tulip glass that resembles Scotland\'s national flower. Benefits: Captures and enhances volatiles, while it induces and supports large foamy heads.',
  'Weizen Glass': 'Nothing beats serving your Weizenbier (wheat beer) in an authentic Bavarian Weizen Glass. These classy glasses, with their thin walls and length, showcase the beer\'s color and allows for much headspace to contain the fluffy, sexy heads association with the style. Most are 0.5L in size, with slight variations in sizes. Forget the lemon garnish, the citric will kill the head. Benefits: Specifically produced to take on volume and head, while locking in the banana-like and phenol aromas associated with the style.',
  'Oversized Wine Glass': '"A wine glass for beer!?" Yep, an oversized 22oz wine glass will be most suitable for serving most Belgian Ales. Its size allows for headspace, while the open bowl creates an amazing nose. A lot of smart beer bars are now serving their Belgian Ales in these. It also makes for a great crossover conversational piece. "Is that wine that you\'re drinking?" And you reply, "No, it\'s De Ranke XX Bitter from Belgium. Wanna try?" Benefits: Replacement for a Tulip or Goblet. Conversational.'
};

module.exports = glassDetails;